#file: noinspection YAMLSchemaValidation
openapi: 3.0.3
info:
  title: GarageFlow
  description: CRM system
  version: 0.0.3
servers:
  - url: 'http://localhost:8080/api'
    description: Local server
paths:
  /users:
  /cars:
  /orders:
