version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    container_name: backend2
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./ENV/.env.common
      - ./ENV/.env.dev
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    depends_on:
      - redis

  redis:
    container_name: redis2
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis-caches:
    container_name: redis-caches2
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_caches_data:/data
    restart: unless-stopped

  redis-commander1:
    container_name: redis-commander2
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  celery:
    build: ./
    command: celery -A config worker -Q notification
    volumes:
      - ./:/app
    env_file:
      - ./ENV/.env.common
      - ./ENV/.env.dev
    depends_on:
      - backend
      - redis

  celery-fast:
    build: ./
    command: celery -A config worker
    container_name: 'celery_fast_tasks'
    volumes:
      - ./:/app
    env_file:
      - ./ENV/.env.common
      - ./ENV/.env.dev
    depends_on:
      - backend
      - redis

  celery-beat:
    build: ./
    command: celery -A config beat
    container_name: 'celery_beat'
    volumes:
      - ./:/app
    env_file:
      - ./ENV/.env.common
      - ./ENV/.env.dev
    depends_on:
      - backend
      - redis

  flower:
    build: ./
    command: celery flower -A config --port=5555 --broker=redis://redis:6379/0
    container_name: 'flower'
    ports:
      - "5555:5555"
    env_file:
      - ./ENV/.env.common
      - ./ENV/.env.dev
    depends_on:
      - backend
      - redis
      - celery

volumes:
  postgres_data:
  redis_data:
  redis_caches_data:
