[mypy]
ignore_missing_imports = True
warn_return_any = False

[mypy-apps.*.migrations.*]
ignore_errors = True

[mypy-apps.*.tests.*]
ignore_errors = True

[mypy-config.*.settings*]
ignore_errors = True