[mypy]
ignore_missing_imports = True
allow_untyped_decorators = True
warn_no_return = False
follow_imports = skip

[mypy-apps.*.migrations.*]
ignore_errors = True

[mypy-apps.*.tests.*]
ignore_errors = True

[mypy-config.*.settings*]
ignore_errors = True