# Generated by Django 5.0.3 on 2025-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена услуги')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не начата'), (1, 'В работе'), (2, 'Готово')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
