# Generated by Django 5.0.3 on 2025-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
    ]
