# Generated by Django 5.0.3 on 2025-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_year_alter_car_number_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Год выпуска'),
        ),
    ]
