# Generated by Django 5.0.3 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2000, max_length=5, null=True, verbose_name='Год выпуска'),
        ),
    ]
