# Generated by Django 5.0.3 on 2025-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Год выпуска'),
        ),
    ]
