# Generated by Django 5.0.3 on 2026-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0013_alter_car_mark_alter_car_model_alter_car_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(
                default="", max_length=100, verbose_name="VIN/Номер кузова"
            ),
        ),
    ]
