# Generated by Django 5.0.3 on 2025-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='-', max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'Administrator'), (1, 'Worker'), (2, 'User')], default=2, verbose_name='Role in system'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_login',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Login in Telegramm'),
        ),
    ]
