# Generated by Django 5.0.3 on 2025-06-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_number_user_role_user_tg_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='-', max_length=15, verbose_name='Phone Number'),
        ),
    ]
