# Generated by Django 5.0.3 on 2025-04-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_work_status'),
        ('workstatus', '0004_alter_workstatus_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_name', to='work.work', verbose_name='Работа'),
        ),
    ]
