# Generated by Django 5.0.3 on 2025-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstatus', '0006_workstatus_amount_workstatus_fix_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='fix_price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
