# Generated by Django 5.0.3 on 2025-04-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0009_alter_order_car_alter_order_owner_alter_order_worker'),
        ('work', '0003_remove_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не начата'), (1, 'В работе'), (2, 'Готово')], default=0, verbose_name='Статус')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_works', to='order.order', verbose_name='Заяка')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_name', to='work.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
