# Generated by Django 5.0.3 on 2025-04-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstatus', '0002_alter_workstatus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstatus',
            options={'verbose_name': 'Статус работы', 'verbose_name_plural': 'Статусы работ'},
        ),
    ]
