# Generated by Django 5.0.3 on 2025-04-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_works_remove_order_workstatus'),
        ('workstatus', '0005_alter_workstatus_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='fix_price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заявка'),
        ),
    ]
