# Generated by Django 5.0.3 on 2025-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_car_alter_order_owner_alter_order_worker'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='works',
            field=models.ManyToManyField(related_name='order_work', to='work.work', verbose_name='Работы'),
        ),
    ]
