# Generated by Django 5.0.3 on 2025-04-14 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10, verbose_name='Номер')),
                ('mark', models.CharField(default='', max_length=50, verbose_name='Марка')),
                ('model', models.CharField(default='', max_length=50, verbose_name='Модель')),
                ('vin', models.CharField(default='', max_length=100, verbose_name='VIN/Номер кузова')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='ID владельца')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
