# Generated by Django 5.0.3 on 2025-04-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
