# Generated by Django 5.0.3 on 2025-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_works'),
        ('work', '0003_remove_work_status'),
        ('workstatus', '0003_alter_workstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workstatus',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_work', to='workstatus.workstatus', verbose_name='Статусы работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='works',
            field=models.ManyToManyField(related_name='order_work', to='work.work', verbose_name='Работы'),
        ),
    ]
