# Generated by Django 5.0.3 on 2025-04-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='workstatus',
        ),
    ]
