# Generated by Django 5.0.3 on 2025-04-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_workstatuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='workstatuses',
            new_name='workstatus',
        ),
    ]
