# Generated by Django 5.0.3 on 2025-04-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_workstatuses_order_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='works',
        ),
        migrations.RemoveField(
            model_name='order',
            name='workstatus',
        ),
    ]
