name: MyPyLint

on:
  push:
    paths:
      - '**/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: '.'
          mypy_flags: '--strict'
