name: lint

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run mypy
        uses: tsuyoshicho/action-mypy@v4
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
	  reporter: github-check
          fail_on_error: true
          setup_method: install
          setup_command: 'pip install -r requirements.txt'
          mypy_flags: "--strict"
  pep8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pep8
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
